stages:
  - test

image: python:3.8-slim
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
cache:
  paths:
    - .cache

before_script:
    - python -m pip cache info
    - pip install poetry==1.2.0
    - poetry config virtualenvs.in-project true
    - poetry config cache-dir $CI_PROJECT_DIR/.cache
    - poetry config virtualenvs.path .venv
    - poetry config --list
    - poetry install
    - source .venv/bin/activate

build-test-and-lint:
  stage: test
  tags:
    - aime
  script:
    - bash test.sh
