[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "supa-recast"
description = "supa-recast, python client to save your data to a running recast server"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
    { name = "WOGRA AG", email = "info@wogra.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "pydantic >=1.6.2,!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/wogra-ag/supa-recast"
Documentation = "https://wogra-ag.github.io/supa-recast"

[project.optional-dependencies]
test = [
    "pytest >=7.1.3,<8.0.0",
    "pytest-cov >=2.12.0,<4.0.0",
    "flake8 >=3.8.3,<6.0.0",
    "black == 22.8.0",
    "isort >=5.0.6,<6.0.0",
]
doc = [
    "mkdocs >=1.1.2,<2.0.0",
    "mkdocs-material >=8.1.4,<9.0.0",
    "mdx-include >=1.4.1,<2.0.0",
    "mkdocs-markdownextradata-plugin >=0.1.7,<0.3.0",
    "typer[all] >=0.6.1,<0.7.0",
    "pyyaml >=5.3.1,<7.0.0",
]
dev = [
    "flake8 >=3.8.3,<6.0.0",
    "pre-commit >=2.17.0,<3.0.0",
]
all = [
    "pyyaml >=5.3.1,<7.0.0",
]

[tool.hatch.version]
path = "supa-recast/__init__.py"

[tool.isort]
profile = "black"
known_third_party = ["pydantic"]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "supa-recast.tests.*"
ignore_missing_imports = true
check_untyped_defs = true

[tool.pytest.ini_options]
addopts = [
  "--strict-config",
  "--strict-markers",
]
xfail_strict = true
junit_family = "xunit2"
filterwarnings = [
    "error"
]
